// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: demo.proto

package com.nonpool.proto;

public interface FrameOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Frame)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string messageType = 1;</code>
   */
  java.lang.String getMessageType();
  /**
   * <code>string messageType = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageTypeBytes();

  /**
   * <code>bytes payload = 15;</code>
   */
  com.google.protobuf.ByteString getPayload();
}
