// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: demo.proto

package com.nonpool.proto;

public interface TextMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TextMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string text = 1;</code>
   */
  java.lang.String getText();
  /**
   * <code>string text = 1;</code>
   */
  com.google.protobuf.ByteString
      getTextBytes();
}
